### ISSUE TITLE
Differentiate between invalid units and invalid byte values

### ISSUE THREAD

**Issue by tcdowney** [XenoPhex/palm_civet#1]
Hello @XenoPhex,

First of all, thanks for working on Palm Civet ☕️!

We're trying to consume your gem, but having some difficulty handling invalid input because the  `InvalidByteQuantityError` error is too broad.

We have our own validations handling non-positive integers, but would like to use Palm Civet to determine if the requested unit is incorrect. Could you either make discrete errors for these cases or stop validating the integer itself?

Your biggest fans,
Tim && @vitreuz

**Comment by tcdowney** [comment]
We submitted a PR: https://github.com/XenoPhex/palm_civet/pull/2

**Comment by XenoPhex** [comment]
Merged into release 1.1.0.
